sudo: required
language: java
jdk:
  - openjdk8
branches:
  only:
  - master
before_install:
- mkdir -p ~/.m2; wget -q -O ~/.m2/settings.xml https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/travis_maven_settings.xml
- sudo mkdir -p /data/lucene; sudo wget -O /data/lucene/namematching-20200214.tgz https://biocache.ala.org.au/archives/nameindexes/20200214/namematching-20200214.tgz
- cd /data/lucene
- sudo tar zxvf namematching-20200214.tgz
- sudo ln -s namematching-20200214 namematching
- ls -laF
- cd $TRAVIS_BUILD_DIR

script:
- "[ \"${TRAVIS_PULL_REQUEST}\" = \"false\" ] && mvn clean install deploy || mvn clean install"

env:
  global:
  - secure: qr79sMF1IBiAoOLH5xzVDNELq7a/XwxxXciMg7sq1s8sLNMsk3x0k+k7jT8+BmJWD+WsmfOuJYrXUzeKQvtnnw2ypGSBgGnIVTZ0Wad6uBnKL9uCtEy2HoD2/OSMkRHV3WUm0GjN8vPdJV7XxLl7sFq14uoOFj8DGtmoj1UFr5w=
  - secure: wINS9pkWlAiBPibL0FW6rOlArS9BpIR46zfOeBeqlxNTDVLy42BjreAkN+84hdqDnD3uIjmVGemB1lWtsKG7gh950mnryTJem0+scnM9Tv01ACKPlRGuCg5If+opA/0UpxZJ1cMI2E8kwlcYGK3IuSBe7YwNGwOplSBuo+/4gJo=
